# Generated by Django 6.0.3 on 2026-03-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'cinema',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show')], max_length=20)),
                ('language', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('aggregate_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=100, unique=True)),
                ('platform_type', models.CharField(blank=True, max_length=20, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'platform',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season_number', models.IntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('total_episodes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('preferred_language', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='showboxd.media')),
                ('box_office_revenue', models.BigIntegerField(blank=True, null=True)),
                ('theatrical_release', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='showboxd.media')),
                ('total_seasons', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
            ],
            options={
                'db_table': 'tv_show',
            },
        ),
        migrations.CreateModel(
            name='MediaGenre',
            fields=[
                ('pk', models.CompositePrimaryKey('media', 'genre', blank=True, editable=False, primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.genre')),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.media')),
            ],
            options={
                'db_table': 'media_genre',
            },
        ),
        migrations.CreateModel(
            name='MediaSimilarity',
            fields=[
                ('similarity_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pk', models.CompositePrimaryKey('media_1', 'media_2', blank=True, editable=False, primary_key=True, serialize=False)),
                ('media_1', models.ForeignKey(db_column='media_id_1', on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_1', to='showboxd.media')),
                ('media_2', models.ForeignKey(db_column='media_id_2', on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_2', to='showboxd.media')),
            ],
            options={
                'db_table': 'media_similarity',
            },
        ),
        migrations.CreateModel(
            name='CastCrew',
            fields=[
                ('role', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('writer', 'Writer'), ('producer', 'Producer'), ('composer', 'Composer'), ('cinematographer', 'Cinematographer')], max_length=50)),
                ('character_name', models.CharField(blank=True, max_length=150, null=True)),
                ('pk', models.CompositePrimaryKey('media', 'person', 'role', blank=True, editable=False, primary_key=True, serialize=False)),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.media')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.person')),
            ],
            options={
                'db_table': 'cast_crew',
            },
        ),
        migrations.CreateModel(
            name='MediaPlatform',
            fields=[
                ('region', models.CharField(max_length=100)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('pk', models.CompositePrimaryKey('media', 'platform', 'region', blank=True, editable=False, primary_key=True, serialize=False)),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.media')),
                ('platform', models.ForeignKey(db_column='platform_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.platform')),
            ],
            options={
                'db_table': 'media_platform',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.media')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.users')),
            ],
            options={
                'db_table': 'review',
                'unique_together': {('media', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.AutoField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=50)),
                ('total_seats', models.IntegerField()),
                ('screen_type', models.CharField(max_length=30, null=True)),
                ('cinema', models.ForeignKey(db_column='cinema_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.cinema')),
            ],
            options={
                'db_table': 'screen',
                'unique_together': {('cinema', 'screen_name')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.AutoField(primary_key=True, serialize=False)),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.media')),
                ('season', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.season')),
            ],
            options={
                'db_table': 'episode',
                'unique_together': {('season', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('showing_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('available_seats', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screen', models.ForeignKey(db_column='screen_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.screen')),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.movie')),
            ],
            options={
                'db_table': 'showing',
                'unique_together': {('screen', 'show_date', 'show_time')},
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('pk', models.CompositePrimaryKey('review', 'user', blank=True, editable=False, primary_key=True, serialize=False)),
                ('review', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.review')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.users')),
            ],
            options={
                'db_table': 'review_like',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats_booked', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('showing', models.ForeignKey(db_column='showing_id', on_delete=django.db.models.deletion.PROTECT, to='showboxd.showing')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.users')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('pk', models.CompositePrimaryKey('user', 'media', 'watched_at', blank=True, editable=False, primary_key=True, serialize=False)),
                ('episode', models.ForeignKey(blank=True, db_column='episode_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='showboxd.episode')),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.media')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.users')),
            ],
            options={
                'db_table': 'watch_history',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.users')),
            ],
            options={
                'db_table': 'watchlist',
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('pk', models.CompositePrimaryKey('watchlist', 'media', blank=True, editable=False, primary_key=True, serialize=False)),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.media')),
                ('watchlist', models.ForeignKey(db_column='watchlist_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.watchlist')),
            ],
            options={
                'db_table': 'watchlist_item',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='media',
            field=models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='showboxd.tvshow'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('media', 'season_number')},
        ),
    ]
