# Generated by Django 6.0.3 on 2026-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showboxd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('media', 'user')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='booking_user_id_acf7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['showing'], name='booking_showing_a5950a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-booking_time'], name='booking_booking_acb153_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status'], name='booking_booking_497d03_idx'),
        ),
        migrations.AddIndex(
            model_name='castcrew',
            index=models.Index(fields=['media'], name='cast_crew_media_i_ccaa32_idx'),
        ),
        migrations.AddIndex(
            model_name='castcrew',
            index=models.Index(fields=['person'], name='cast_crew_person__0de6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='castcrew',
            index=models.Index(fields=['media', 'role'], name='cast_crew_media_i_c33bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='cinema',
            index=models.Index(fields=['city'], name='cinema_city_70b1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='cinema',
            index=models.Index(fields=['region'], name='cinema_region_92d3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'episode_number'], name='episode_season__061e27_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['media'], name='episode_media_i_f777a6_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type'], name='media_media_t_9a1c04_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['release_date'], name='media_release_bfa23b_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['aggregate_rating'], name='media_aggrega_a1c9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['-created_at'], name='media_created_8cc717_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type', 'aggregate_rating'], name='media_media_t_43742f_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['title'], name='media_title_0196e5_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['language'], name='media_languag_8e10dc_idx'),
        ),
        migrations.AddIndex(
            model_name='mediagenre',
            index=models.Index(fields=['media'], name='media_genre_media_i_90393a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediagenre',
            index=models.Index(fields=['genre'], name='media_genre_genre_i_a25336_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaplatform',
            index=models.Index(fields=['region'], name='media_platf_region_d6bd49_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaplatform',
            index=models.Index(fields=['platform', 'region'], name='media_platf_platfor_feb088_idx'),
        ),
        migrations.AddIndex(
            model_name='mediasimilarity',
            index=models.Index(fields=['media_1', '-similarity_score'], name='media_simil_media_i_114144_idx'),
        ),
        migrations.AddIndex(
            model_name='mediasimilarity',
            index=models.Index(fields=['media_2', '-similarity_score'], name='media_simil_media_i_ae51c1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['media'], name='review_media_i_afa231_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='review_user_id_14f41a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-review_date'], name='review_review__844cde_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['media', '-review_date'], name='review_media_i_8d68f7_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlike',
            index=models.Index(fields=['review'], name='review_like_review__9c983c_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlike',
            index=models.Index(fields=['user'], name='review_like_user_id_e28785_idx'),
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['cinema', 'screen_name'], name='screen_cinema__838913_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['media', 'season_number'], name='season_media_i_2d8216_idx'),
        ),
        migrations.AddIndex(
            model_name='showing',
            index=models.Index(fields=['media', 'show_date'], name='showing_media_i_2429d9_idx'),
        ),
        migrations.AddIndex(
            model_name='showing',
            index=models.Index(fields=['show_date', 'show_time'], name='showing_show_da_4dfded_idx'),
        ),
        migrations.AddIndex(
            model_name='showing',
            index=models.Index(fields=['screen', 'show_date'], name='showing_screen__aa9ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['is_verified'], name='users_is_veri_63cd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['region'], name='users_region_8eeced_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['user', 'watched_at'], name='watch_histo_user_id_1964c9_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['media'], name='watch_histo_media_i_93063e_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'visibility'], name='watchlist_user_id_42f2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['watchlist', '-added_at'], name='watchlist_i_watchli_d344f1_idx'),
        ),
    ]
